name: Update Go Dependencies

on:
  push:
    branches:
      - master  # 你可以根据需要更改为其他分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装 Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Update Go dependencies
        run: |
          cd ratelimit
          go get -u ./...  # 更新所有依赖
          go mod tidy      # 清理未使用的依赖

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes"

      - name: 提交更改
        if: steps.check_changes.outputs.changes == 'changes'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add go.mod go.sum
          git commit -m "Update Go dependencies" || echo "No changes to commit"
          git push origin master  # 根据需要更改为目标分支
